management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    env:
      enabled: true
      post:
        enabled: true
    httptrace:
      enabled: true
#  trace:
#    http:
#      enabled: true
