server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false

management:
  endpoint:
    routes:
      enabled: true
    refresh:
      enabled: true
    filters:
      enabled: true
    loggers:
      enabled: true
  endpoints:
   web:
     exposure:
       include: refresh, health, loggers, filters

